title: Mostafa Ashraf
description: "Satellite - jekyll blog theme"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.webp"

# Social Links
email: mostafa.nada1221@gmail.com
github_username: mostafa904
linkedin_username: mostafa-ashraf-17114a1aa

# External API
giscus_repo: 
giscus_repoId: 
giscus_category: 
giscus_categoryId: 
goatcounter_code: 
google_analytics:


# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
